name: main

on:
  push:
    branches:
      - main
      - issue#?**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache registry
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: pdflatex:latest
          outputs: type=docker,dest=/tmp/pdflatex.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate
        run: |
          docker load --input /tmp/pdflatex.tar

          docker image ls

          lang="english"

          docker container run \
          --workdir /tmp \
          --volume ./:/tmp \
          pdflatex \
          pdflatex \
          -output-directory=/tmp \
          -jobname=rafael_dutra_${lang} \
          "\def\lang{${lang}} \
          \input{main}" \
          main.tex

      - name: Cover Letter
        run: |
          docker load --input /tmp/pdflatex.tar

          currentCompany="Fake Company"
          currentPosition="DevOps Engineer"
          desiredCompany="Fake Destiny"
          desiredPosition=SRE

          docker container run \
          --workdir /tmp \
          --volume ./:/tmp \
          pdflatex \
          pdflatex \
          -output-directory=/tmp \
          -jobname=rafael_dutra_cover_letter \
          "\def\currentCompany{${currentCompany}} \
           \def\currentPosition{${currentPosition}} \
           \def\desiredPosition{${desiredPosition}} \
           \def\desiredCompany{${desiredCompany}} \
           \input{cover_letter}" \
          cover_letter.tex
